const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=__dirname;
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///'+root.replaceAll('\\','/')+'/dashboard.html');
for(const mode of ['binary','balanced']){await page.selectOption('#run',mode);const data=JSON.parse(fs.readFileSync(path.join(root,'results',mode+'.json'),'utf8'));const m=data.metrics;assert.equal(await page.locator('#accuracy').textContent(),(m.accuracy*100).toFixed(1)+'%');assert.equal(await page.locator('#macro-f1').textContent(),(m.macro_f1*100).toFixed(1)+'%');assert.deepEqual(await page.locator('#matrix td button').allTextContents(),m.matrix.flat().map(String));assert.equal(await page.locator('#rows tr').count(),m.n);
for(const status of ['correct','mismatch']){await page.selectOption('#status',status);const expected=data.rows.filter(r=>r.correct===(status==='correct')).map(r=>String(r.source_line));assert.equal(await page.locator('#count').textContent(),`${expected.length} of ${m.n} reviews`);assert.deepEqual(await page.locator('#rows tr[data-source-line]').evaluateAll(els=>els.map(el=>el.dataset.sourceLine)),expected)}await page.click('#reset');
for(const actual of m.classes)for(const predicted of m.classes){await page.selectOption('#actual',actual);await page.selectOption('#predicted',predicted);const n=data.rows.filter(r=>r.actual===actual&&r.sentiment===predicted).length;assert.equal(await page.locator('#count').textContent(),`${n} of ${m.n} reviews`)}await page.click('#reset');await page.fill('#search','zzzz-no-match-zzzz');assert.equal(await page.locator('#count').textContent(),`0 of ${m.n} reviews`);await page.click('#reset');
assert.equal(await page.locator('.bar.nonzero').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().width===0).length),0);
if(mode==='balanced'){for(const v of ['agree','differ']){await page.selectOption('#emotion-filter',v);const n=v==='agree'?data.emotion_metrics.agree:m.n-data.emotion_metrics.agree;assert.equal(await page.locator('#count').textContent(),`${n} of ${m.n} reviews`)}await page.click('#reset');}
}
fs.mkdirSync(path.join(root,'screenshots'),{recursive:true});await page.screenshot({path:path.join(root,'screenshots','dashboard.png'),fullPage:true});await page.selectOption('#status','mismatch');await page.locator('#rows').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(root,'screenshots','review-explorer.png')});await page.click('#reset');await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:path.join(root,'screenshots','mobile.png'),fullPage:true});assert.deepEqual(errors,[]);assert(!(await page.locator('body').innerText()).includes('undefined'));fs.writeFileSync(path.join(root,'results','browser_checks.json'),JSON.stringify({passed:true,checks:['headline accuracy and macro F1 match saved output','every confusion matrix cell matches saved output','correct and mismatch filters match exact source lines','every actual/predicted combination has correct count','empty search has zero rows','emotion agreement and disagreement counts match','nonzero bars have visible width','390px mobile viewport has no document overflow','no browser JavaScript errors'],viewports:[{width:1440,height:1100},{width:390,height:844}]},null,2));await browser.close();console.log('PASS: browser figures, filters, bars, mobile layout, screenshots');})();
